# Generated by Django 4.2.5 on 2023-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='menu_title',
        ),
        migrations.AddField(
            model_name='blocks',
            name='text_block',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
