# Generated by Django 4.2.5 on 2023-09-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0003_rename_menu_sort_blocks_block_sort_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocks',
            new_name='Block',
        ),
    ]
