# Generated by Django 4.2.5 on 2023-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0004_rename_blocks_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='text_block',
            field=models.JSONField(),
        ),
    ]
