# Generated by Django 4.2.5 on 2023-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0005_alter_block_text_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='text_block',
            field=models.TextField(max_length=50),
        ),
    ]
