# Generated by Django 4.2.5 on 2023-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0006_alter_block_text_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='text_block',
        ),
        migrations.AddField(
            model_name='block',
            name='text_block_body',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='text_block_footer',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='text_block_header',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
