# Generated by Django 4.2.5 on 2023-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0007_remove_block_text_block_block_text_block_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='text_block_body',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='text_block_footer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='text_block_header',
            field=models.CharField(max_length=10),
        ),
    ]
