# Generated by Django 4.2.5 on 2023-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0008_alter_block_text_block_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='text_block_body',
        ),
        migrations.RemoveField(
            model_name='block',
            name='text_block_footer',
        ),
        migrations.RemoveField(
            model_name='block',
            name='text_block_header',
        ),
        migrations.AddField(
            model_name='block',
            name='text_block',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
