# Generated by Django 4.2.5 on 2023-09-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_main', '0009_remove_block_text_block_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='text_block',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(max_length=100),
        ),
    ]
